server:
  port: @eureka-server.port@
spring:
  application:
    name: @pom.artifactId@
eureka:
  instance:
    hostname: @eureka-server.host@
    prefer-ip-address: true
  server:
      # 关闭自我保护，以确保注册中心将不可用的实例正确剔除
      enable-self-preservation: false
      # 清理服务器
      eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    # 服务提供者 不向eureka 注册
    register-with-eureka: false
    # 不从eureka 拉取服务列表
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
          - autoconfig
          - auditevents
          - beans
          - configprops
          - dump
          - env
          - health
          - info
          - metrics
          - mappings
          - shutdown
          - trace
logging:
  config: classpath:application-log4j2.yml
